---
- name: installing repo for Java 8 in Ubuntu
  apt_repository: repo='ppa:openjdk-r/ppa'
      
- name: run ansible galaxy
  local_action: command ansible-galaxy install -r requirements.yml

- name: geerlingguy.java
  java_packages:
    - java-1.7.0-openjdk